class bacula::params (
  $config_root                = '/etc/bacula',
  $working_dir                = $::osfamily ? {
    /(?i:redhat)/ => '/var/spool/bacula',
    /(?i:debian)/ => '/var/lib/bacula',
  },
  $pid_dir                    = '/var/run/bacula',
  $log_dir                    = '/var/log/bacula',
  $default_user               = 'bacula',
  $default_group              = 'bacula',
  $firewall_source            = '0.0.0.0',
  $firewall_iniface           = undef,
  $firewall_outiface          = undef,
  $dbuser                     = 'bacula',
  $dbpassword                 = 'bacula',
  $dbhost                     = 'localhost',
  $from_email                 = undef,
  $log_email                  = undef,
  $director_server            = 'bacula',
  $director_password          = 'bacula',
  $director_port              = '9101',
  $director_firewall_source   = $::bacula::params::firewall_source,
  $director_firewall_iniface  = $::bacula::params::firewall_iniface,
  $director_firewall_outiface = $::bacula::params::firewall_outiface,
  $director_pkg_name          = 'bacula-director-mysql',
  $director_pkg_version       = 'present',
  $director_service_name      = $::operatingsystem ? {
    centos => 'bacula-dir',
    debian => 'bacula-director',
  },
  $director_service_hasstatus = $::operatingsystem ? {
    default => undef,
    debian  => false,
  },
  $director_service_ensure    = 'running',
  $director_service_enable    = true,
  $db_init_command            = $::operatingsystem ? {
    centos => '/usr/libexec/bacula/make_bacula_tables',
    debian => '/usr/share/bacula-director/make_mysql_tables',
  },
  $dir_max_concurrent_jobs    = '1',
  $dir_messages               = 'bacula-dir',
  $schedules                  = [
    'FullDaily',
    'FullWeekly',
    'IncDaily',
    'IncWeekly',
    'DiffDaily',
    'DiffWeekly',
    'FullMonthlyDiffWeeklyIncDaily',
    'FullWeeklyDiffDailyIncHourly',
    'FullWeeklyIncDaily',
  ],
  $filesets                   = [
    'Catalog',
    'FullSet',
    'MysqlData',
    'Config',
  ],
  $jobdefs                    = [
    'DefaultJob',
    'Mysql',
    'Config',
  ],
  $sd_port                    = '9103',
  $sd_firewall_source         = $::bacula::params::firewall_source,
  $sd_firewall_iniface        = $::bacula::params::firewall_iniface,
  $sd_firewall_outiface       = $::bacula::params::firewall_outiface,
  $storage_dir                = '/mnt/backup',
  $sd_pkg_name                = $::operatingsystem ? {
    default => 'bacula-storage-mysql',
    debian  => 'bacula-sd-mysql',
  },
  $sd_pkg_version             = 'present',
  $sd_service_name            = 'bacula-sd',
  $sd_service_ensure          = 'running',
  $sd_service_enable          = true,
  $sd_service_hasstatus       = $::operatingsystem ? {
    default => undef,
    debian  => false,
  },
  $sd_server                  = "bacula.${::domain}",
  $sd_label                   = 'bacula-sd',
  $sd_password                = 'bacula',
  $sd_owner                   = 'bacula',
  $sd_group                   = 'bacula',
  $sd_max_concurrent_jobs     = '1',
  $sd_messages                = 'bacula-sd',
  $media_type                 = 'File',
  $fd_port                    = '9102',
  $fd_firewall_source         = $::bacula::params::firewall_source,
  $fd_firewall_iniface        = $::bacula::params::firewall_iniface,
  $fd_firewall_outiface       = $::bacula::params::firewall_outiface,
  $fd_password                = 'bacula',
  $fd_max_concurrent_jobs     = '1',
  $fd_messages                = 'bacula-fd',
  $fd_pkg_name                = 'bacula-client',
  $fd_pkg_version             = 'latest',
  $fd_service_name            = 'bacula-fd',
  $fd_service_ensure          = 'running',
  $fd_service_enable          = true,
  $fd_service_hasstatus       = true,
  $bconsole_pkgname           = 'bacula-console',
  $catalog                    = 'DefaultCatalog',
  $messages_mailcommand       = '',
  $messages_operatorcommand   = '',
  $default_pool               = 'FullPool',
  $default_jobtype            = 'Backup',
  $default_jobdefs            = 'DefaultJob',
  $default_storage            = "${::fqdn}-storage",
  $default_fullpool           = 'FullPool',
  $default_incrementalpool    = 'IncrementalPool',
  $default_fileset            = 'FullSet',
  $default_schedule           = 'FullWeekly',
  $device_owner               = 'bacula',
  $device_group               = 'bacula',
) {
}
